# -*- coding: utf-8 -*-
"""wto_co2_china_v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iubVFMOGzXM8iD7Mhti149d2eyFMqYat

# 🌍 WTO成员身份与出口碳排放强度
## ——基于1995-2025年面板数据的双重差分分析

| 项目 | 内容 |
|------|------|
| **数据来源** | EDGAR v8.0 · World Bank WDI · WTO官网 |
| **研究方法** | 双重差分法 (DiD) + 固定效应模型 |
| **研究期间** | 1995–2025年 |
| **核心问题** | 加入WTO是否降低了出口碳排放强度？|

---
### 📋 运行顺序
**第一步** → 安装库  
**第二步** → 加载数据（EDGAR + 出口 + WDI + WTO）  
**第三步** → 构建面板数据集  
**第四步** → 描述性统计  
**第五步** → DiD回归分析  
**第六步** → 事件研究图（平行趋势检验）  
**第七步** → 异质性分析  
**第八步** → 稳健性检验

---
## 第一步 · 安装与导入库
"""

# 安装所需库（只需运行一次）
!pip install pandas numpy matplotlib scipy openpyxl

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import matplotlib.font_manager as fm
import zipfile
import warnings
from scipy import stats
from scipy.stats import t as t_dist
warnings.filterwarnings('ignore')

# ── 研究期间配置（全局参数）─────────────────────────────────────────────
# 修改此处即可调整整个分析的研究期间，所有数据加载与可视化均会随之更新。
START_YEAR = 1995   # 研究起始年份
END_YEAR   = 2025   # 研究结束年份

# ── 中文字体设置（Google Colab专用）─────────────────────────────────────
# 方法1：优先使用WenQuanYi（简体中文支持最佳）
import os

def setup_chinese_font():
    """
    在Google Colab中设置中文字体。
    依次尝试：WenQuanYi → Noto Sans CJK SC → 下载备用字体
    """
    # 搜索可用的中文字体
    candidates = []
    for font in fm.fontManager.ttflist:
        if any(x in font.name for x in ['WenQuanYi', 'Noto Sans CJK SC',
                                          'Noto Sans CJK', 'Noto Serif CJK SC',
                                          'SimHei', 'SimSun', 'Microsoft YaHei']):
            candidates.append((font.name, font.fname))

    if candidates:
        chosen_name, chosen_path = candidates[0]
        # 直接注册字体文件
        prop = fm.FontProperties(fname=chosen_path)
        plt.rcParams['font.family'] = prop.get_name()
        plt.rcParams['font.sans-serif'] = [prop.get_name()] + plt.rcParams.get('font.sans-serif', [])
        print(f'✅ 使用中文字体: {chosen_name}')
        print(f'   字体路径: {chosen_path}')
        return chosen_path
    else:
        # 备用方案：安装字体
        print('⚠️  未找到中文字体，尝试安装...')
        os.system('apt-get install -y fonts-wqy-zenhei fonts-noto-cjk > /dev/null 2>&1')
        fm.fontManager.__init__()
        return setup_chinese_font()

FONT_PATH = setup_chinese_font()

# 全局matplotlib设置
plt.rcParams.update({
    'axes.unicode_minus': False,   # 修复负号显示
    'font.size':          11,
    'axes.spines.top':    False,
    'axes.spines.right':  False,
    'axes.grid':          True,
    'grid.alpha':         0.3,
    'grid.linestyle':     '--',
    'figure.dpi':         130,
})

# 辅助函数：在每个图中应用中文字体属性
CN_FONT = fm.FontProperties(fname=FONT_PATH) if FONT_PATH else None

def cn(size=11, bold=False):
    """返回中文字体属性对象，用于text/title/label等"""
    if CN_FONT is None:
        return {}
    props = fm.FontProperties(fname=FONT_PATH, size=size,
                               weight='bold' if bold else 'normal')
    return {'fontproperties': props}

# 颜色方案
BLUE  = '#2166ac'
RED   = '#d6604d'
GREEN = '#1a9850'
GRAY  = '#737373'
GOLD  = '#b8860b'

print('✅ 所有库导入成功')
print('   提示：如果图表仍显示方块，请重启运行环境后重新运行此单元格')

"""---
## 第二步 · 加载数据

**文件路径说明：** 请将以下4个文件放在与本notebook相同的目录下：

| 文件名 | 来源 | 已上传? |
|--------|------|---------|
| `EDGAR_2025_GHG_booklet_2025_fossilCO2only.xlsx` | EDGAR v8.0 | ✅ |
| `API_NE_EXP_GNFS_CD_DS2_en_csv_v2_313730.zip` | World Bank | ✅ |
| `P_Data_Extract_From_World_Development_Indicators.zip` | World Bank WDI | ✅ |
| WTO成员数据（内嵌在代码中） | WTO官网 | ✅ |
"""

# ── 2A. CO₂排放数据 (EDGAR v8.0) ─────────────────────────────────────
print('正在加载EDGAR CO₂数据...')

df_edgar = pd.read_excel(
    '/content/EDGAR_2025_GHG_booklet_2025_fossilCO2only.xlsx',
    sheet_name='fossil_CO2_totals_by_country'
)
df_edgar = df_edgar.rename(columns={
    'EDGAR Country Code': 'iso3',
    'Country': 'country_name'
})

# 提取研究期间（START_YEAR–END_YEAR）的年份列
year_cols = [c for c in df_edgar.columns
             if isinstance(c, (int, float)) and START_YEAR <= int(c) <= END_YEAR]

# 转为长格式
df_co2 = df_edgar[['iso3'] + year_cols].melt(
    id_vars='iso3', var_name='year', value_name='co2_mt')
df_co2['year']   = df_co2['year'].astype(int)
df_co2['co2_mt'] = pd.to_numeric(df_co2['co2_mt'], errors='coerce')
df_co2 = df_co2.dropna(subset=['co2_mt'])

# 去除非国家行（国际航空、航运等）
exclude_codes = ['AIR', 'SEA', 'AIR+SEA', 'GLOBAL', 'ANT']
df_co2 = df_co2[~df_co2['iso3'].isin(exclude_codes)]

print(f'✅ CO₂数据: {len(df_co2):,}行 | {df_co2["iso3"].nunique()}个国家')
df_co2.head(3)

# ── 2B. 出口数据 (World Bank) ─────────────────────────────────────────
print('正在加载出口数据...')

with zipfile.ZipFile('/content/API_NE.EXP.GNFS.CD_DS2_en_csv_v2_313730.zip') as z:
    with z.open('API_NE.EXP.GNFS.CD_DS2_en_csv_v2_313730.csv') as f:
        df_exp_raw = pd.read_csv(f, skiprows=4)

df_exp_raw = df_exp_raw.rename(columns={'Country Code': 'iso3'})
yr_cols = [c for c in df_exp_raw.columns
           if str(c).isdigit() and START_YEAR <= int(c) <= END_YEAR]

df_exp = df_exp_raw[['iso3'] + yr_cols].melt(
    id_vars='iso3', var_name='year', value_name='export_usd')
df_exp['year']       = df_exp['year'].astype(int)
df_exp['export_usd'] = pd.to_numeric(df_exp['export_usd'], errors='coerce')
df_exp = df_exp.dropna(subset=['export_usd'])
df_exp = df_exp[df_exp['export_usd'] > 0]

print(f'✅ 出口数据: {len(df_exp):,}行 | {df_exp["iso3"].nunique()}个国家')
df_exp.head(3)

# ── 2C. 控制变量 (World Bank WDI) ────────────────────────────────────
print('正在加载WDI控制变量...')

with zipfile.ZipFile('/content/P_Data_Extract_From_World_Development_Indicators.zip') as z:
    fname = [n for n in z.namelist() if n.endswith('_Data.csv')][0]
    with z.open(fname) as f:
        df_wdi_raw = pd.read_csv(f)

df_wdi_raw = df_wdi_raw.dropna(subset=['Series Code'])

yr_wdi = [c for c in df_wdi_raw.columns
          if 'YR' in str(c)
          and START_YEAR <= int(c.split('[')[1].replace('YR','').replace(']','')) <= END_YEAR]

df_wdi_l = df_wdi_raw[['Country Code', 'Series Code'] + yr_wdi].melt(
    id_vars=['Country Code', 'Series Code'],
    var_name='yr_raw', value_name='value')
df_wdi_l['year']  = df_wdi_l['yr_raw'].str.extract(r'(\d{4})').astype(int)
df_wdi_l['value'] = pd.to_numeric(df_wdi_l['value'], errors='coerce')

df_wdi = df_wdi_l.pivot_table(
    index=['Country Code', 'year'],
    columns='Series Code',
    values='value'
).reset_index()
df_wdi.columns.name = None
df_wdi = df_wdi.rename(columns={
    'Country Code':     'iso3',
    'NY.GDP.PCAP.KD':   'gdp_pc',
    'EG.EGY.PRIM.PP.KD':'energy_intensity',
    'NV.IND.TOTL.ZS':   'industry_share'
})

print(f'✅ WDI数据: {len(df_wdi):,}行 | 指标: {[c for c in df_wdi.columns if c not in ["iso3","year"]]}')
df_wdi.head(3)

# ── 2D. WTO成员数据（来自WTO官网，已整理） ─────────────────────────────
print('正在构建WTO成员数据库...')

# 数据来源：https://www.wto.org/english/thewto_e/whatis_e/tif_e/org6_e.htm
wto_data = {
    'AFG':2016,'ALB':2000,'AGO':1996,'ATG':1995,'ARG':1995,'ARM':2003,
    'AUS':1995,'AUT':1995,'BHR':1995,'BGD':1995,'BRB':1995,'BEL':1995,
    'BLZ':1995,'BEN':1996,'BOL':1995,'BWA':1995,'BRA':1995,'BRN':1995,
    'BGR':1996,'BFA':1995,'BDI':1995,'CPV':2008,'KHM':2004,'CMR':1995,
    'CAN':1995,'CAF':1995,'TCD':1996,'CHL':1995,'CHN':2001,'COL':1995,
    'COG':1997,'CRI':1995,'CIV':1995,'HRV':2000,'CUB':1995,'CYP':1995,
    'CZE':1995,'COD':1997,'DNK':1995,'DJI':1995,'DMA':1995,'DOM':1995,
    'ECU':1996,'EGY':1995,'SLV':1995,'EST':1999,'SWZ':1995,'FJI':1996,
    'FIN':1995,'FRA':1995,'GAB':1995,'GMB':1996,'GEO':2000,'DEU':1995,
    'GHA':1995,'GRC':1995,'GRD':1996,'GTM':1995,'GIN':1995,'GNB':1995,
    'GUY':1995,'HTI':1996,'HND':1995,'HKG':1995,'HUN':1995,'ISL':1995,
    'IND':1995,'IDN':1995,'IRL':1995,'ISR':1995,'ITA':1995,'JAM':1995,
    'JPN':1995,'JOR':2000,'KAZ':2015,'KEN':1995,'KOR':1995,'KWT':1995,
    'KGZ':1998,'LAO':2013,'LVA':1999,'LSO':1995,'LBR':2016,'LIE':1995,
    'LTU':2001,'LUX':1995,'MAC':1995,'MDG':1995,'MWI':1995,'MYS':1995,
    'MDV':1995,'MLI':1995,'MLT':1995,'MRT':1995,'MUS':1995,'MEX':1995,
    'MDA':2001,'MNG':1997,'MNE':2012,'MAR':1995,'MOZ':1995,'MMR':1995,
    'NAM':1995,'NPL':2004,'NLD':1995,'NZL':1995,'NIC':1995,'NER':1996,
    'NGA':1995,'MKD':2003,'NOR':1995,'OMN':2000,'PAK':1995,'PAN':1997,
    'PNG':1996,'PRY':1995,'PER':1995,'PHL':1995,'POL':1995,'PRT':1995,
    'QAT':1996,'ROU':1995,'RUS':2012,'RWA':1996,'SAU':2005,'SEN':1995,
    'SLE':1995,'SGP':1995,'SVK':1995,'SVN':1995,'SLB':1996,'ZAF':1995,
    'ESP':1995,'LKA':1995,'SUR':1995,'SWE':1995,'CHE':1995,'TJK':2013,
    'TZA':1995,'THA':1995,'TLS':2024,'TGO':1995,'TON':2007,'TTO':1995,
    'TUN':1995,'TUR':1995,'UGA':1995,'UKR':2008,'ARE':1996,'GBR':1995,
    'USA':1995,'URY':1995,'VUT':2012,'VEN':1995,'VNM':2007,'YEM':2014,
    'ZMB':1995,'ZWE':1995
}

df_wto = pd.DataFrame(list(wto_data.items()), columns=['iso3', 'year_joined'])
print(f'✅ WTO成员: {len(df_wto)}个国家')
print(f'   1995年后加入: {(df_wto["year_joined"] > 1995).sum()}个')
print(f'   主要晚加入国: 中国(2001), 沙特(2005), 越南(2007), 俄罗斯(2012), 哈萨克斯坦(2015)')
df_wto[df_wto['year_joined'] > 2000].sort_values('year_joined').head(10)

"""---
## 第三步 · 构建面板数据集

**核心变量：出口碳排放强度**

$$\text{CO}_2\text{强度}_{it} = \frac{\text{CO}_2排放量_{it}\;(\text{吨})}{\text{出口额}_{it}\;(\text{百万美元})}$$

**DiD处理变量：**
$$\text{WTO}_{it} = \begin{cases} 1 & \text{若国家}i\text{在}t\text{年已是WTO成员} \\ 0 & \text{否则} \end{cases}$$
"""

print('── 构建面板数据集 ──')

# 1. 合并CO₂与出口数据
panel = df_co2.merge(df_exp, on=['iso3', 'year'], how='inner')

# 2. 计算CO₂强度（吨/百万美元出口）
#    co2_mt单位为百万吨 → 转换为吨: ×1e6
#    export_usd单位为美元 → 转换为百万美元: ÷1e6
panel['co2_intensity'] = (panel['co2_mt'] * 1e6) / (panel['export_usd'] / 1e6)
panel = panel[panel['co2_intensity'] > 0]
panel['ln_co2'] = np.log(panel['co2_intensity'])  # 取对数

# 3. 添加WTO成员信息
panel = panel.merge(df_wto, on='iso3', how='left')
panel['wto_member'] = (
    panel['year_joined'].notna() &
    (panel['year'] >= panel['year_joined'])
).astype(int)
panel['treated']    = (panel['year_joined'] > 1995).astype(int)  # 1995年后加入=处理组
panel['event_time'] = panel['year'] - panel['year_joined']        # 相对入世时间

# 4. 添加控制变量
panel = panel.merge(df_wdi, on=['iso3', 'year'], how='left')
panel['ln_gdp_pc']  = np.log(panel['gdp_pc'].clip(lower=1))
panel['ln_gdp_pc2'] = panel['ln_gdp_pc'] ** 2  # 用于检验EKC曲线

# 5. 去除缺失关键变量的行
panel_clean = panel.dropna(subset=['ln_co2', 'wto_member'])

print(f'观测值数量 : {len(panel_clean):,}')
print(f'国家数量   : {panel_clean["iso3"].nunique()}')
print(f'研究期间   : {panel_clean["year"].min()}–{panel_clean["year"].max()}')
print(f'WTO成员比例: {panel_clean["wto_member"].mean()*100:.1f}%')
print(f'处理组国家 : {panel_clean[panel_clean["treated"]==1]["iso3"].nunique()}个（1995年后加入）')
panel_clean[['iso3','year','co2_mt','export_usd','co2_intensity','ln_co2','wto_member']].head(5)

"""---
## 第四步 · 描述性统计与可视化
"""

# ── 描述性统计表 ──────────────────────────────────────────────────────
vars_cn = {
    'co2_intensity':  'CO₂强度（吨/百万美元）',
    'ln_co2':         'ln(CO₂强度)',
    'wto_member':     'WTO成员（0/1）',
    'co2_mt':         'CO₂排放量（百万吨）',
    'export_usd':     '出口额（美元）',
    'gdp_pc':         '人均GDP（2015美元）',
    'energy_intensity':'能源强度',
    'industry_share': '工业占GDP比重（%）',
}

rows = []
for col, label in vars_cn.items():
    if col in panel_clean.columns:
        s = panel_clean[col].describe()
        rows.append({
            '变量': label,
            '观测值': int(s['count']),
            '均值': round(s['mean'], 3),
            '标准差': round(s['std'], 3),
            '最小值': round(s['min'], 3),
            '中位数': round(s['50%'], 3),
            '最大值': round(s['max'], 3),
        })

desc_df = pd.DataFrame(rows)
desc_df.to_csv('表1_描述性统计.csv', index=False, encoding='utf-8-sig')
print('✅ 已保存: 表1_描述性统计.csv')
desc_df

# ── 图1: 处理组与控制组的CO₂强度趋势 ─────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# 左图：趋势对比
ax1 = axes[0]
group_labels = {0: ('控制组（1995年加入WTO）', BLUE),
                1: ('处理组（1995年后加入WTO）', RED)}
for grp, (label, color) in group_labels.items():
    data = (panel_clean[panel_clean['treated'] == grp]
            .groupby('year')['ln_co2'].mean())
    ax1.plot(data.index, data.values, label=label,
             color=color, linewidth=2.5, marker='o', markersize=4)

ax1.set_title('图1a  CO₂强度趋势：处理组 vs 控制组', **cn(12, bold=True), pad=10)
ax1.set_xlabel('年份', **cn(11))
ax1.set_ylabel('ln(CO₂强度)', **cn(11))
ax1.legend(prop=fm.FontProperties(fname=FONT_PATH, size=9) if CN_FONT else None)
ax1.set_xticks(range(START_YEAR, END_YEAR + 1, 5))

# 右图：分布直方图
ax2 = axes[1]
ax2.hist(panel_clean['ln_co2'].dropna(), bins=50,
         color=BLUE, alpha=0.75, edgecolor='white')
mean_val = panel_clean['ln_co2'].mean()
ax2.axvline(mean_val, color=RED, lw=2, linestyle='--',
            label=f'均值={mean_val:.2f}')
ax2.set_title('图1b  ln(CO₂出口强度)分布', **cn(12, bold=True), pad=10)
ax2.set_xlabel('ln(吨CO₂/百万美元出口)', **cn(11))
ax2.set_ylabel('频率', **cn(11))
ax2.legend(prop=fm.FontProperties(fname=FONT_PATH, size=9) if CN_FONT else None)

plt.suptitle('图1  描述性统计图', **cn(13, bold=True), y=1.02)
plt.tight_layout()
plt.savefig('图1_描述性统计.png', bbox_inches='tight', dpi=150)
plt.show()
print('✅ 已保存: 图1_描述性统计.png')

# ── 图2: 主要国家CO₂强度变化（START_YEAR vs END_YEAR）──────────────────
focus_countries = {
    'CHN': '中国', 'IND': '印度', 'USA': '美国', 'DEU': '德国',
    'RUS': '俄罗斯', 'BRA': '巴西', 'ZAF': '南非', 'KOR': '韩国',
    'IDN': '印度尼西亚', 'MEX': '墨西哥'
}

plot_data = []
for iso, name in focus_countries.items():
    for yr in [START_YEAR, END_YEAR]:
        row = panel_clean[(panel_clean['iso3'] == iso) & (panel_clean['year'] == yr)]
        if not row.empty:
            plot_data.append({'国家': name, '年份': yr,
                              'CO₂强度': row['co2_intensity'].values[0]})

df_plot = pd.DataFrame(plot_data)

if not df_plot.empty:
    fig, ax = plt.subplots(figsize=(12, 5))
    countries = df_plot['国家'].unique()
    x = np.arange(len(countries))
    width = 0.35

    for i, (yr, color) in enumerate([(START_YEAR, BLUE), (END_YEAR, RED)]):
        vals = [df_plot[(df_plot['国家']==c) & (df_plot['年份']==yr)]['CO₂强度'].values
                for c in countries]
        vals = [v[0] if len(v) > 0 else 0 for v in vals]
        ax.bar(x + i*width - width/2, vals, width,
               label=f'{yr}年', color=color, alpha=0.8)

    ax.set_xticks(x)
    cn_prop = fm.FontProperties(fname=FONT_PATH, size=10) if CN_FONT else None
    ax.set_xticklabels(countries,
                       fontproperties=cn_prop)
    ax.set_title(f'图2  主要国家出口CO₂强度：{START_YEAR}年与{END_YEAR}年对比',
                 **cn(12, bold=True), pad=10)
    ax.set_ylabel('CO₂强度（吨/百万美元）', **cn(11))
    ax.legend(prop=fm.FontProperties(fname=FONT_PATH, size=10) if CN_FONT else None)
    plt.tight_layout()
    plt.savefig('图2_主要国家对比.png', bbox_inches='tight', dpi=150)
    plt.show()
    print('✅ 已保存: 图2_主要国家对比.png')

"""---
## 第五步 · DiD 双重差分回归

**基准模型：**
$$\ln(\text{CO}_2\text{强度}_{it}) = \beta_0 + \beta_1 \cdot \text{WTO}_{it} + \beta_2 \ln(\text{人均GDP}_{it}) + \beta_3 [\ln(\text{人均GDP}_{it})]^2 + \beta_4 \text{能源强度}_{it} + \alpha_i + \gamma_t + \varepsilon_{it}$$

**三种回归规格：**
- (1) 混合OLS（无固定效应）
- (2) 国家固定效应
- (3) 双向固定效应：国家 + 年份 ← **核心模型 ★**

**手动实现双向固定效应（demean法）：**
"""

# ── 回归辅助函数 ──────────────────────────────────────────────────────

def ols_with_se(X, y, cluster_ids=None):
    """
    OLS回归，支持聚类标准误（国家层面）。
    返回：系数、标准误、t值、p值
    """
    X = np.array(X, dtype=float)
    y = np.array(y, dtype=float)
    n, k = X.shape

    # OLS系数
    XtX_inv = np.linalg.pinv(X.T @ X)
    beta = XtX_inv @ X.T @ y
    resid = y - X @ beta

    if cluster_ids is not None:
        # 聚类稳健标准误（Cluster-Robust SE）
        clusters = np.unique(cluster_ids)
        G = len(clusters)
        meat = np.zeros((k, k))
        for g in clusters:
            idx = cluster_ids == g
            Xg = X[idx]
            eg = resid[idx]
            score = Xg.T @ eg
            meat += np.outer(score, score)
        # Small-sample correction
        correction = (G / (G - 1)) * (n - 1) / (n - k)
        vcov = correction * XtX_inv @ meat @ XtX_inv
    else:
        s2 = (resid @ resid) / (n - k)
        vcov = s2 * XtX_inv

    se = np.sqrt(np.diag(vcov))
    tstat = beta / se
    pval  = 2 * (1 - t_dist.cdf(np.abs(tstat), df=n - k))
    r2    = 1 - np.var(resid) / np.var(y)
    return {'beta': beta, 'se': se, 'tstat': tstat, 'pval': pval,
            'resid': resid, 'r2': r2, 'n': n}


def within_demean(df, dep, indep, entity_col, time_col):
    """
    双向固定效应去均值（within transformation）。
    y_it - ȳ_i - ȳ_t + ȳ
    """
    d = df[[entity_col, time_col, dep] + indep].dropna().copy()
    for col in [dep] + indep:
        grand_mean  = d[col].mean()
        entity_mean = d.groupby(entity_col)[col].transform('mean')
        time_mean   = d.groupby(time_col)[col].transform('mean')
        d[col] = d[col] - entity_mean - time_mean + grand_mean
    return d


def stars(p):
    return '***' if p < 0.01 else '**' if p < 0.05 else '*' if p < 0.1 else ''


print('✅ 回归函数已定义')

# ── 准备回归数据 ──────────────────────────────────────────────────────
dep_var = 'ln_co2'
controls = [c for c in ['ln_gdp_pc', 'ln_gdp_pc2', 'energy_intensity', 'industry_share']
            if c in panel_clean.columns and panel_clean[c].notna().sum() > 200]
indep    = ['wto_member'] + controls

df_reg = panel_clean[['iso3', 'year', dep_var] + indep].dropna()
cluster_ids = df_reg['iso3'].values

print(f'回归样本: {len(df_reg):,}行 | 国家: {df_reg["iso3"].nunique()} | 控制变量: {controls}')

# ── (1) 混合OLS ────────────────────────────────────────────────────────
X1 = np.column_stack([np.ones(len(df_reg)),
                      df_reg[indep].values])
y1 = df_reg[dep_var].values
res1 = ols_with_se(X1, y1, cluster_ids)

# ── (2) 国家固定效应（entity demean）──────────────────────────────────
df_fe = df_reg.copy()
for col in [dep_var] + indep:
    df_fe[col] = df_fe[col] - df_fe.groupby('iso3')[col].transform('mean')
X2 = np.column_stack([df_fe[indep].values])
y2 = df_fe[dep_var].values
res2 = ols_with_se(X2, y2, cluster_ids)

# ── (3) 双向固定效应（entity + time demean）★ ─────────────────────────
df_twfe = within_demean(df_reg, dep_var, indep, 'iso3', 'year')
X3 = df_twfe[indep].values
y3 = df_twfe[dep_var].values
res3 = ols_with_se(X3, y3, cluster_ids[:len(y3)])

# ── 结果汇总表 ────────────────────────────────────────────────────────
var_labels_cn = {
    'wto_member':     'WTO成员（β₁）',
    'ln_gdp_pc':      'ln(人均GDP)',
    'ln_gdp_pc2':     '[ln(人均GDP)]²',
    'energy_intensity':'能源强度',
    'industry_share': '工业增加值占比',
}

print('\n' + '='*72)
print('                  表2  回归结果：WTO成员身份对CO₂强度的影响')
print('='*72)
print(f'{"变量":<22} {"(1)混合OLS":>16} {"(2)国家FE":>16} {"(3)双向FE★":>16}')
print('-'*72)

rows_table = []
for i, var in enumerate(indep):
    label = var_labels_cn.get(var, var)

    # Model 1: intercept at index 0, then indep
    b1, s1, p1 = res1['beta'][i+1], res1['se'][i+1], res1['pval'][i+1]
    # Model 2 & 3: no intercept
    b2, s2, p2 = res2['beta'][i], res2['se'][i], res2['pval'][i]
    b3, s3, p3 = res3['beta'][i], res3['se'][i], res3['pval'][i]

    print(f'{label:<22} {b1:>10.4f}{stars(p1):>3}  {b2:>10.4f}{stars(p2):>3}  {b3:>10.4f}{stars(p3):>3}')
    print(f'{"":<22} {"("+str(round(s1,4))+")":>13}  {"("+str(round(s2,4))+")":>13}  {"("+str(round(s3,4))+")":>13}')

    rows_table.append({'变量': label,
                       '(1)混合OLS': f'{b1:.4f}{stars(p1)}',
                       '(1)SE': f'({s1:.4f})',
                       '(2)国家FE': f'{b2:.4f}{stars(p2)}',
                       '(2)SE': f'({s2:.4f})',
                       '(3)双向FE': f'{b3:.4f}{stars(p3)}',
                       '(3)SE': f'({s3:.4f})'})

print('-'*72)
print(f'{"国家固定效应":<22} {"否":>16} {"是":>16} {"是":>16}')
print(f'{"年份固定效应":<22} {"否":>16} {"否":>16} {"是":>16}')
print(f'{"观测值":<22} {res1["n"]:>16,} {res2["n"]:>16,} {res3["n"]:>16,}')
print(f'{"R²":<22} {res1["r2"]:>16.4f} {res2["r2"]:>16.4f} {res3["r2"]:>16.4f}')
print('='*72)
print('注：括号内为聚类稳健标准误（国家层面）。*** p<0.01，** p<0.05，* p<0.1')

pd.DataFrame(rows_table).to_csv('表2_回归结果.csv', index=False, encoding='utf-8-sig')
print('\n✅ 已保存: 表2_回归结果.csv')

# ── 核心结果解读 ──────────────────────────────────────────────────────
wto_idx = indep.index('wto_member')
b_main = res3['beta'][wto_idx]
p_main = res3['pval'][wto_idx]
s_main = res3['se'][wto_idx]
effect_pct = (np.exp(b_main) - 1) * 100
sig = ('*** (p<0.01)' if p_main < 0.01 else '** (p<0.05)' if p_main < 0.05
       else '* (p<0.1)' if p_main < 0.1 else '不显著')

print('=' * 60)
print('★  核心结果解读（双向固定效应模型）')
print('=' * 60)
print(f'   β(wto_member) = {b_main:.4f}   {sig}')
print(f'   标准误         = {s_main:.4f}')
print(f'   经济含义：加入WTO使CO₂强度变动 {effect_pct:+.2f}%')
print(f'            （exp({b_main:.4f}) - 1 = {effect_pct/100:.4f}）')
print()
if b_main < 0 and p_main < 0.1:
    print('   → 支持「技术转移假说」✅')
    print('   → WTO充当出口清洁化的「绿色渠道」')
elif b_main > 0 and p_main < 0.1:
    print('   → 支持「污染天堂假说」⚠️')
    print('   → 加入WTO与较高碳排放强度相关')
else:
    print('   → 效应不显著')
    print('   → WTO成员身份对CO₂强度影响不确定')

"""---
## 第六步 · 事件研究图
### ——平行趋势检验

**模型：**
$$\ln(\text{CO}_2\text{强度}_{it}) = \sum_{\tau \neq -1} \delta_\tau \cdot \mathbf{1}(\text{event\_time}_{it}=\tau) + \alpha_i + \gamma_t + \varepsilon_{it}$$

**判断标准：**
- 入世前系数 $\delta_\tau$（$\tau < 0$）统计上 ≈ 0 → **平行趋势成立** ✅
- 入世后系数持续为负 → **WTO降低了CO₂强度** ✅
"""

# ── 事件研究法 ────────────────────────────────────────────────────────
T_MIN, T_MAX = -6, 6

# 仅使用处理组（1995年后加入WTO的国家）
df_es = panel_clean[
    (panel_clean['treated'] == 1) &
    (panel_clean['event_time'] >= T_MIN) &
    (panel_clean['event_time'] <= T_MAX)
].copy()

print(f'事件研究样本: {len(df_es):,}行 | {df_es["iso3"].nunique()}个处理组国家')

# 创建事件时间虚拟变量（以t=-1为基期）
times = list(range(T_MIN, T_MAX + 1))
dummy_names = []
for t in times:
    if t != -1:
        col = f'et_pos{t}' if t >= 0 else f'et_neg{abs(t)}'
        df_es[col] = (df_es['event_time'] == t).astype(int)
        dummy_names.append(col)

# 双向去均值
es_vars = dummy_names + [c for c in ['ln_gdp_pc'] if c in df_es.columns]
df_es_dm = within_demean(df_es, 'ln_co2', es_vars, 'iso3', 'year')

X_es = df_es_dm[es_vars].values
y_es = df_es_dm['ln_co2'].values
cids = df_es[['iso3']].loc[df_es_dm.index, 'iso3'].values

res_es = ols_with_se(X_es, y_es, cids)

# 整理系数
coefs, ses, times_plot = [], [], []
dummy_list = []
for t in times:
    col = f'et_pos{t}' if t >= 0 else f'et_neg{abs(t)}'
    if t == -1:
        coefs.append(0); ses.append(0)
    elif col in es_vars:
        idx = es_vars.index(col)
        coefs.append(res_es['beta'][idx])
        ses.append(res_es['se'][idx])
    else:
        coefs.append(np.nan); ses.append(np.nan)
    times_plot.append(t)

coefs = np.array(coefs)
ses   = np.array(ses)
ci95  = 1.96 * ses

# ── 绘制事件研究图 ────────────────────────────────────────────────────
fig, ax = plt.subplots(figsize=(12, 6))

# 背景阴影
ax.axvspan(T_MIN - 0.5, -1.5, alpha=0.06, color=BLUE, label='入世前期')
ax.axvspan(-0.5, T_MAX + 0.5, alpha=0.06, color=GREEN, label='入世后期')

# 95%置信区间
ax.fill_between(times_plot,
                coefs - ci95,
                coefs + ci95,
                alpha=0.2, color=RED)

# 分段绘制
pre_idx  = [i for i, t in enumerate(times_plot) if t < 0]
post_idx = [i for i, t in enumerate(times_plot) if t >= 0]

ax.plot([times_plot[i] for i in pre_idx],
        [coefs[i] for i in pre_idx],
        'o-', color=BLUE, linewidth=2.5, markersize=7,
        label='入世前（应接近0，验证平行趋势）')
ax.plot([times_plot[i] for i in post_idx],
        [coefs[i] for i in post_idx],
        's-', color=RED, linewidth=2.5, markersize=7,
        label='入世后（WTO政策效应）')

ax.axvline(x=0, color='black', linestyle='--', linewidth=1.8,
           label='入世时间（t=0）', alpha=0.8)
ax.axhline(y=0, color=GRAY, linewidth=0.8, alpha=0.5)

# 标注
ax.text(-5.5, ax.get_ylim()[1]*0.85 if not np.all(np.isnan(coefs)) else 0.1,
        '平行趋势检验区域\n（系数应≈0）',
        fontproperties=fm.FontProperties(fname=FONT_PATH, size=9) if CN_FONT else None,
        color=BLUE, alpha=0.8)

ax.set_xlabel('距入世时间（年）', **cn(12))
ax.set_ylabel('系数δ（对ln CO₂强度的影响）', **cn(12))
ax.set_title('图3  事件研究图：WTO入世对出口CO₂强度的动态影响\n'
             '（95%置信区间，聚类稳健标准误）',
             **cn(13, bold=True), pad=10)
ax.legend(prop=fm.FontProperties(fname=FONT_PATH, size=9) if CN_FONT else None, loc='upper left')
ax.set_xticks(times_plot)
ax.set_xticklabels([f't={t}' for t in times_plot], fontsize=9)

plt.tight_layout()
plt.savefig('图3_事件研究图.png', bbox_inches='tight', dpi=150)
plt.show()
print('✅ 已保存: 图3_事件研究图.png')

# 平行趋势检验结论
pre_coefs_valid = [coefs[i] for i in pre_idx if i > 0 and not np.isnan(coefs[i])]
pre_pvals = []
for t in times_plot:
    if t < -1:
        col = f'et_neg{abs(t)}'
        if col in es_vars:
            idx = es_vars.index(col)
            pre_pvals.append(res_es['pval'][idx])

n_sig = sum(p < 0.1 for p in pre_pvals)
print(f'\n平行趋势检验: 入世前{len(pre_pvals)}个系数中，{n_sig}个在10%水平上显著')
print('✅ 平行趋势假设成立！' if n_sig == 0 else '⚠️ 部分前期系数显著，需谨慎解释')

"""---
## 第七步 · 异质性分析
"""

# ── 异质性分析：发达国家 vs 发展中国家 ─────────────────────────────────
DEVELOPED = {
    'AUS','AUT','BEL','CAN','CHL','CZE','DNK','FIN','FRA','DEU',
    'GRC','HUN','ISL','IRL','ISR','ITA','JPN','KOR','LUX','MEX',
    'NLD','NZL','NOR','POL','PRT','SVK','ESP','SWE','CHE','TUR','GBR','USA'
}

panel_h = panel_clean.copy()
panel_h['developed'] = panel_h['iso3'].isin(DEVELOPED).astype(int)

# 按能源强度高低分组
groups = {}
groups['发达国家']   = panel_h[panel_h['developed'] == 1]
groups['发展中国家'] = panel_h[panel_h['developed'] == 0]
if 'energy_intensity' in panel_h.columns:
    med_ei = panel_h['energy_intensity'].median()
    groups['高能源强度国家'] = panel_h[panel_h['energy_intensity'] >  med_ei]
    groups['低能源强度国家'] = panel_h[panel_h['energy_intensity'] <= med_ei]

het_results = []
print(f'{"分组":<18} {"β(WTO)":>10} {"标准误":>10} {"p值":>10} {"效应%":>10} {"N":>8}')
print('-' * 65)

for gname, sub in groups.items():
    if len(sub) < 100:
        continue
    sub_vars = [v for v in indep if v in sub.columns and sub[v].notna().sum() > 50]
    df_sub = within_demean(sub, 'ln_co2', sub_vars, 'iso3', 'year')
    if len(df_sub) < 50:
        continue
    Xs = df_sub[sub_vars].values
    ys = df_sub['ln_co2'].values
    cids_s = sub[['iso3']].loc[df_sub.index, 'iso3'].values
    try:
        res_s = ols_with_se(Xs, ys, cids_s)
        widx  = sub_vars.index('wto_member')
        b, s, p = res_s['beta'][widx], res_s['se'][widx], res_s['pval'][widx]
        pct = (np.exp(b) - 1) * 100
        print(f'{gname:<18} {b:>10.4f} {s:>10.4f} {p:>10.4f} {pct:>+10.1f}% {res_s["n"]:>8,}')
        het_results.append({'分组': gname, 'β': b, 'SE': s, 'p值': p,
                            '显著性': stars(p), '效应%': pct, 'N': res_s['n']})
    except Exception as e:
        print(f'  ⚠️ {gname}: {e}')

het_df = pd.DataFrame(het_results)
print('-' * 65)
print('注：*** p<0.01，** p<0.05，* p<0.1')

# ── 图4：异质性分析可视化 ─────────────────────────────────────────────
if not het_df.empty:
    fig, ax = plt.subplots(figsize=(10, 4))

    colors = [RED if b > 0 else BLUE for b in het_df['β']]
    y_pos  = range(len(het_df))

    ax.barh(y_pos, het_df['β'],
            xerr=het_df['SE'] * 1.96,
            color=colors, alpha=0.75, height=0.5,
            error_kw={'elinewidth': 2, 'capsize': 5, 'ecolor': GRAY})

    ax.axvline(x=0, color='black', linewidth=1)
    ax.set_yticks(list(y_pos))
    cn_prop = fm.FontProperties(fname=FONT_PATH, size=11) if CN_FONT else None
    ax.set_yticklabels(het_df['分组'].tolist(),
                       fontproperties=cn_prop)

    cn_prop9 = fm.FontProperties(fname=FONT_PATH, size=10) if CN_FONT else None
    for i, (v, sig, pct) in enumerate(zip(het_df['β'], het_df['显著性'], het_df['效应%'])):
        offset = 0.008 if v >= 0 else -0.008
        ax.text(v + offset, i,
                f'{sig} ({pct:+.1f}%)',
                va='center',
                ha='left' if v >= 0 else 'right',
                fontproperties=cn_prop9)

    ax.set_xlabel('回归系数β（95%置信区间）', **cn(11))
    ax.set_title('图4  WTO效应的异质性分析\n（正值=污染天堂，负值=技术转移）',
                 **cn(12, bold=True), pad=10)

    plt.tight_layout()
    plt.savefig('图4_异质性分析.png', bbox_inches='tight', dpi=150)
    plt.show()
    print('✅ 已保存: 图4_异质性分析.png')

"""---
## 第八步 · 稳健性检验

| 检验方法 | 目的 | 通过标准 |
|---------|------|----------|
| **(A)** 安慰剂检验 | 排除随机性 | β_安慰剂 ≈ 0 |
| **(B)** 排除中国 | 检验中国主导效应 | 系数方向一致 |
| **(C)** 去除极端值 | 检验离群值影响 | 系数稳定 |
"""

# ── (A) 安慰剂检验（500次随机入世日期）────────────────────────────────
print('[A] 安慰剂检验（运行500次，请稍候）...')
np.random.seed(2024)

placebo_betas = []
years_pool    = panel_clean['year'].unique()
treated_isos  = panel_clean[panel_clean['treated'] == 1]['iso3'].unique()

for _ in range(500):
    pc = panel_clean.copy()
    # 随机分配虚假入世年份
    fake_years = {iso: np.random.choice(years_pool) for iso in treated_isos}
    pc['wto_fake'] = pc.apply(
        lambda row: 1 if (row['iso3'] in fake_years
                         and row['year'] >= fake_years[row['iso3']]) else 0, axis=1)

    fake_indep = ['wto_fake'] + [c for c in controls if c in pc.columns]
    try:
        df_p = within_demean(pc, 'ln_co2', fake_indep, 'iso3', 'year')
        Xp   = df_p[fake_indep].values
        yp   = df_p['ln_co2'].values
        resp = ols_with_se(Xp, yp)
        placebo_betas.append(resp['beta'][0])
    except:
        pass

placebo_betas = np.array([b for b in placebo_betas if not np.isnan(b)])
real_beta = res3['beta'][wto_idx]
p_placebo = np.mean(placebo_betas <= real_beta)

print(f'\n   真实β         = {real_beta:.4f}')
print(f'   安慰剂均值β   = {placebo_betas.mean():.4f}')
print(f'   安慰剂p值     = {p_placebo:.3f}')
print('   ✅ 效应非随机！' if p_placebo < 0.05 else '   ⚠️ 安慰剂未被拒绝，检查数据')

# 绘制安慰剂分布图
fig, ax = plt.subplots(figsize=(9, 4))
ax.hist(placebo_betas, bins=40, color=GRAY, alpha=0.7,
        edgecolor='white', label='安慰剂系数（500次随机实验）')
ax.axvline(real_beta, color=RED, lw=2.5, linestyle='--',
           label=f'真实β = {real_beta:.4f}')
ax.axvline(0, color='black', lw=0.8, alpha=0.5)
ax.set_xlabel('β系数', **cn(11))
ax.set_ylabel('频率', **cn(11))
ax.set_title('图5  安慰剂检验：随机入世日期的系数分布',
             **cn(12, bold=True), pad=10)
ax.legend(prop=fm.FontProperties(fname=FONT_PATH, size=9) if CN_FONT else None)
plt.tight_layout()
plt.savefig('图5_安慰剂检验.png', bbox_inches='tight', dpi=150)
plt.show()
print('✅ 已保存: 图5_安慰剂检验.png')

# ── (B) 排除中国 ──────────────────────────────────────────────────────
print('[B] 排除中国（CHN）')
no_cn   = panel_clean[panel_clean['iso3'] != 'CHN']
nc_vars = [v for v in indep if v in no_cn.columns and no_cn[v].notna().sum() > 100]
df_nc   = within_demean(no_cn, 'ln_co2', nc_vars, 'iso3', 'year')
Xnc     = df_nc[nc_vars].values
ync     = df_nc['ln_co2'].values
res_nc  = ols_with_se(Xnc, ync, no_cn[['iso3']].loc[df_nc.index,'iso3'].values)
wi      = nc_vars.index('wto_member')
b_nc, p_nc = res_nc['beta'][wi], res_nc['pval'][wi]
print(f'   β = {b_nc:.4f}{stars(p_nc)}  (p = {p_nc:.4f})  N = {res_nc["n"]:,}')
print('   ✅ 排除中国后结果稳健' if p_nc < 0.1 else '   ⚠️ 排除中国后显著性下降')

# ── (C) 去除极端值（上下1%）───────────────────────────────────────────
print('\n[C] 去除极端值（上下1%）')
q1, q99   = panel_clean['ln_co2'].quantile([0.01, 0.99])
trimmed   = panel_clean[(panel_clean['ln_co2'] >= q1) & (panel_clean['ln_co2'] <= q99)]
tr_vars   = [v for v in indep if v in trimmed.columns]
df_tr     = within_demean(trimmed, 'ln_co2', tr_vars, 'iso3', 'year')
Xtr, ytr  = df_tr[tr_vars].values, df_tr['ln_co2'].values
res_tr    = ols_with_se(Xtr, ytr, trimmed[['iso3']].loc[df_tr.index,'iso3'].values)
wt        = tr_vars.index('wto_member')
b_tr, p_tr = res_tr['beta'][wt], res_tr['pval'][wt]
print(f'   删除观测值: {len(panel_clean) - len(trimmed)}')
print(f'   β = {b_tr:.4f}{stars(p_tr)}  (p = {p_tr:.4f})  N = {res_tr["n"]:,}')
print('   ✅ 排除极端值后结果稳健' if p_tr < 0.1 else '   ⚠️ 结果对极端值敏感')

# ── 稳健性汇总 ────────────────────────────────────────────────────────
print('\n' + '='*55)
print('          稳健性检验汇总')
print('='*55)
robust_summary = pd.DataFrame([
    {'检验方案': '基准模型（双向FE）',  'β': real_beta,
     '效应%': (np.exp(real_beta)-1)*100, 'p值': res3['pval'][wto_idx]},
    {'检验方案': '排除中国',            'β': b_nc,
     '效应%': (np.exp(b_nc)-1)*100,     'p值': p_nc},
    {'检验方案': '去除极端值(1%)',       'β': b_tr,
     '效应%': (np.exp(b_tr)-1)*100,     'p值': p_tr},
]).round(4)
print(robust_summary.to_string(index=False))
robust_summary.to_csv('表3_稳健性检验.csv', index=False, encoding='utf-8-sig')
print('\n✅ 已保存: 表3_稳健性检验.csv')

"""---
## 结果汇总与输出文件清单
"""

print('=' * 60)
print('🎓  分析完成！所有输出文件：')
print('=' * 60)
print('  📊 图1_描述性统计.png      — 趋势图 + 分布图')
print('  📊 图2_主要国家对比.png    — 主要国家CO₂强度对比')
print('  📊 图3_事件研究图.png      — 平行趋势检验（核心图）')
print('  📊 图4_异质性分析.png      — 发达/发展中国家异质性')
print('  📊 图5_安慰剂检验.png      — 安慰剂检验分布图')
print('  📄 表1_描述性统计.csv      — 描述性统计表')
print('  📄 表2_回归结果.csv        — DiD回归结果表')
print('  📄 表3_稳健性检验.csv      — 稳健性检验汇总表')
print()
print('★ 核心结论：')
b_final = res3['beta'][wto_idx]
p_final = res3['pval'][wto_idx]
pct_final = (np.exp(b_final) - 1) * 100
print(f'   WTO成员身份使出口CO₂强度变动 {pct_final:+.2f}%')
print(f'   β = {b_final:.4f}, {stars(p_final) or "不显著"}')
if b_final < 0 and p_final < 0.1:
    print('   → 支持技术转移假说：WTO是出口清洁化的「绿色渠道」✅')
elif b_final > 0 and p_final < 0.1:
    print('   → 支持污染天堂假说：WTO加剧了碳排放不均衡⚠️')
else:
    print('   → 总体效应不显著，存在异质性（见第七步）')